### ISSUE TITLE
Update to Bedmachine v5

### ISSUE THREAD

**Issue by signehl** [GEUS-Glaciology-and-Climate/ice_discharge#37]
https://nsidc.org/data/idbmg4

**Comment by mankoff** [comment]
I just saw this announcement too and came here to open a ticket :).

Based on the "Version Summary"  there should not be any changes - but because it should be a drag-and-drop replacement (with maybe editing the code in 1 or 2 places to load the new filename), the update should still be done. If there are differences from this update, it may be worth reporting back to @/mmorligh and NSIDC.

> This data set is the same as Version 4 with the following changes:
> 
> 
> 
>     Added bathymetry measurements from the Alfred Wegener Institute,
>     Helmholtz Centre for Polar and Marine Research, in front of the Northeast Greenland Ice Stream
> 
>     Added ice thickness for ice caps from Millan et al. (2022) (https://www.nature.com/articles/s41561-021-00885-z)
> 
>     Included bathymetry data from NASA's 2021 Oceans Melting Greenland (OMG) campaign
> 
>     Provided a geotiff file of bed elevation

**Comment by mankoff** [comment]
Duplicated. Closed in #33.
